In [1]:
#Load pandas

import pandas as pd

In [2]:
#data is a dictionary containing two lists
#pd.DataFrame(data) turns it into a table

data = {
    "country": ["France", "Germany", "United Kingdom"],
    "population": [61083916, 82400996, 60776238]
}

df = pd.DataFrame(data)
df

          country  population
0          France    61083916
1         Germany    82400996
2  United Kingdom    60776238

In [3]:
df["country"]

0            France
1           Germany
2    United Kingdom
Name: country, dtype: str

In [4]:
df["population"]

0    61083916
1    82400996
2    60776238
Name: population, dtype: int64

In [5]:
#Check which populations exceed 70 million
df["population"] > 70000000

0    False
1     True
2    False
Name: population, dtype: bool

In [6]:
#To display the matching row put the condition inside a df
df[df["population"] > 70000000]

   country  population
1  Germany    82400996

In [7]:
#Display the rows where the population is less than 70 million. 
df[df["population"] < 70000000]

          country  population
0          France    61083916
2  United Kingdom    60776238

In [8]:
#Display the row where country is "France", using the same df[condition] structure.
df[df["country"] == "France"]

  country  population
0  France    61083916

In [9]:
#Next exercise: Display all rows where the country is not Germany.
#Python uses != for “not equal to.”
df[df["country"] != "Germany"] #df[condition]  # Keep the rows where the condition is True

          country  population
0          France    61083916
2  United Kingdom    60776238

In [10]:
#Display all rows where the population is greater than 60 million.
df[df["population"] > 60000000]

          country  population
0          France    61083916
1         Germany    82400996
2  United Kingdom    60776238

### Sorting a table

In [11]:
df.sort_values("population", ascending=False)

          country  population
1         Germany    82400996
0          France    61083916
2  United Kingdom    60776238

In [12]:
#Sort the table by population from smallest to largest, using ascending=True.
df.sort_values("population", ascending=True)

          country  population
2  United Kingdom    60776238
0          France    61083916
1         Germany    82400996

In [13]:
#Sort the table by country name alphabetically, A–Z, using sort_values().
df.sort_values("country")

          country  population
0          France    61083916
1         Germany    82400996
2  United Kingdom    60776238

### Calculate a total

In [14]:
df["population"].sum()

np.int64(204261150)

### Calculate average

In [15]:
df["population"].mean()

np.float64(68087050.0)

In [16]:
#Find the largest population in the column using .max().
df["population"].max()

np.int64(82400996)

In [17]:
#In this way, we can also show the country that has the largest population.
df[df["population"] == df["population"].max()]

   country  population
1  Germany    82400996

In [18]:
#Display the row for the country with the smallest population.
df[df["population"] == df["population"].min()]

          country  population
2  United Kingdom    60776238

In [19]:
#Display the rows where population is greater than the average population.
df[df["population"] > df["population"].mean()]

   country  population
1  Germany    82400996

### Loading CSV file

In [20]:
import pandas as pd

development_df = pd.read_csv("development_2007.csv")
development_df.head()

       country  year continent       pop  lifeExp     gdpPercap
0  Afghanistan  2007      Asia  31889923   43.828    974.580338
1      Albania  2007    Europe   3600523   76.423   5937.029526
2      Algeria  2007    Africa  33333216   72.301   6223.367465
3       Angola  2007    Africa  12420476   42.731   4797.231267
4    Argentina  2007  Americas  40301927   75.320  12779.379640

In [21]:
#Check the table's size
development_df.shape

(142, 6)

In [22]:
#Inspect the columns types and missing value counts
development_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    142 non-null    str
 1   year       142 non-null    int64
 2   continent  142 non-null    str
 3   pop        142 non-null    int64
 4   lifeExp    142 non-null    float64
 5   gdpPercap  142 non-null    float64
dtypes: float64(2), int64(2), str(2)
memory usage: 6.8 KB

In [23]:
#Next exercise: Display the rows where continent is "Europe".
development_df[development_df["continent"] == "Europe"]

                    country  year continent       pop  lifeExp     gdpPercap
1                   Albania  2007    Europe   3600523   76.423   5937.029526
6                   Austria  2007    Europe   8199783   79.829  36126.492700
9                   Belgium  2007    Europe  10392226   79.441  33692.605080
12   Bosnia and Herzegovina  2007    Europe   4552198   74.852   7446.298803
15                 Bulgaria  2007    Europe   7322858   73.005  10680.792820
31                  Croatia  2007    Europe   4493312   75.748  14619.222720
33           Czech Republic  2007    Europe  10228744   76.486  22833.308510
34                  Denmark  2007    Europe   5468120   78.332  35278.418740
43                  Finland  2007    Europe   5238460   79.313  33207.084400
44                   France  2007    Europe  61083916   80.657  30470.016700
47                  Germany  2007    Europe  82400996   79.406  32170.374420
49                   Greece  2007    Europe  10706290   79.483  27538.411880
56                  Hungary  2007    Europe   9956108   73.338  18008.944440
57                  Iceland  2007    Europe    301931   81.757  36180.789190
62                  Ireland  2007    Europe   4109086   78.885  40675.996350
64                    Italy  2007    Europe  58147733   80.546  28569.719700
84               Montenegro  2007    Europe    684736   74.543   9253.896111
90              Netherlands  2007    Europe  16570613   79.762  36797.933320
95                   Norway  2007    Europe   4627926   80.196  49357.190170
102                  Poland  2007    Europe  38518241   75.563  15389.924680
103                Portugal  2007    Europe  10642836   78.098  20509.647770
106                 Romania  2007    Europe  22276056   72.476  10808.475610
111                  Serbia  2007    Europe  10150265   74.002   9786.534714
114         Slovak Republic  2007    Europe   5447502   74.663  18678.314350
115                Slovenia  2007    Europe   2009245   77.926  25768.257590
118                   Spain  2007    Europe  40448191   80.941  28821.063700
122                  Sweden  2007    Europe   9031088   80.884  33859.748350
123             Switzerland  2007    Europe   7554661   81.701  37506.419070
131                  Turkey  2007    Europe  71158647   71.777   8458.276384
133          United Kingdom  2007    Europe  60776238   79.425  33203.261280

In [24]:
#Saving the above rows for reuse:
europe_df = development_df[development_df["continent"] == "Europe"]

In [25]:
#Sort values to display these countries by lifeExp highest to lowest
europe_df.sort_values("lifeExp", ascending=False)

                    country  year continent       pop  lifeExp     gdpPercap
57                  Iceland  2007    Europe    301931   81.757  36180.789190
123             Switzerland  2007    Europe   7554661   81.701  37506.419070
118                   Spain  2007    Europe  40448191   80.941  28821.063700
122                  Sweden  2007    Europe   9031088   80.884  33859.748350
44                   France  2007    Europe  61083916   80.657  30470.016700
64                    Italy  2007    Europe  58147733   80.546  28569.719700
95                   Norway  2007    Europe   4627926   80.196  49357.190170
6                   Austria  2007    Europe   8199783   79.829  36126.492700
90              Netherlands  2007    Europe  16570613   79.762  36797.933320
49                   Greece  2007    Europe  10706290   79.483  27538.411880
9                   Belgium  2007    Europe  10392226   79.441  33692.605080
133          United Kingdom  2007    Europe  60776238   79.425  33203.261280
47                  Germany  2007    Europe  82400996   79.406  32170.374420
43                  Finland  2007    Europe   5238460   79.313  33207.084400
62                  Ireland  2007    Europe   4109086   78.885  40675.996350
34                  Denmark  2007    Europe   5468120   78.332  35278.418740
103                Portugal  2007    Europe  10642836   78.098  20509.647770
115                Slovenia  2007    Europe   2009245   77.926  25768.257590
33           Czech Republic  2007    Europe  10228744   76.486  22833.308510
1                   Albania  2007    Europe   3600523   76.423   5937.029526
31                  Croatia  2007    Europe   4493312   75.748  14619.222720
102                  Poland  2007    Europe  38518241   75.563  15389.924680
12   Bosnia and Herzegovina  2007    Europe   4552198   74.852   7446.298803
114         Slovak Republic  2007    Europe   5447502   74.663  18678.314350
84               Montenegro  2007    Europe    684736   74.543   9253.896111
111                  Serbia  2007    Europe  10150265   74.002   9786.534714
56                  Hungary  2007    Europe   9956108   73.338  18008.944440
15                 Bulgaria  2007    Europe   7322858   73.005  10680.792820
106                 Romania  2007    Europe  22276056   72.476  10808.475610
131                  Turkey  2007    Europe  71158647   71.777   8458.276384

In [26]:
#Display only the top five European countries by life expectancy.
#Add .head(5) after your sort_values(...) call. 
#This works like SQL’s ORDER BY ... DESC LIMIT 5.
europe_df.sort_values("lifeExp", ascending=False).head(5)

         country  year continent       pop  lifeExp    gdpPercap
57       Iceland  2007    Europe    301931   81.757  36180.78919
123  Switzerland  2007    Europe   7554661   81.701  37506.41907
118        Spain  2007    Europe  40448191   80.941  28821.06370
122       Sweden  2007    Europe   9031088   80.884  33859.74835
44        France  2007    Europe  61083916   80.657  30470.01670

In [27]:
#Next exercise: Using the full development_df table, display the five countries with the largest populations.
development_df.sort_values("pop", ascending=False).head(5)

           country  year continent         pop  lifeExp     gdpPercap
24           China  2007      Asia  1318683096   72.961   4959.114854
58           India  2007      Asia  1110396331   64.698   2452.210407
134  United States  2007  Americas   301139947   78.242  42951.653090
59       Indonesia  2007      Asia   223547000   70.650   3540.651564
14          Brazil  2007  Americas   190010647   72.390   9065.800825

### Pandas’ equivalent of SQL’s GROUP BY

In [28]:
development_df.groupby("continent")["pop"].sum()

continent
Africa       929539692
Americas     898871184
Asia        3811953827
Europe       586098529
Oceania       24549947
Name: pop, dtype: int64

In [29]:
#Calculate the average life expectancy (lifeExp) for each continent.
development_df.groupby("continent")["lifeExp"].mean()

continent
Africa      54.806038
Americas    73.608120
Asia        70.728485
Europe      77.648600
Oceania     80.719500
Name: lifeExp, dtype: float64

In [30]:
#Next exercise: Sort these averages from highest to lowest.
#First I'm saving the above rows filtered for reuse:
average_df = development_df.groupby("continent")["lifeExp"].mean()
#Now I'm sorting the values:
average_df.sort_values(ascending=False)

continent
Oceania     80.719500
Europe      77.648600
Americas    73.608120
Asia        70.728485
Africa      54.806038
Name: lifeExp, dtype: float64

### Check for repeated pairs

In [31]:
development_df.duplicated(subset=["country", "year"]).sum()

np.int64(0)

In [32]:
#Running this to see individual checks
development_df.duplicated(subset=["country", "year"])

0      False
1      False
2      False
3      False
4      False
       ...
137    False
138    False
139    False
140    False
141    False
Length: 142, dtype: bool

### Counting missing values

In [33]:
#.isna() marks missing values as True.
#.sum() counts those marks separately for each column.
development_df.isna().sum()

country      0
year         0
continent    0
pop          0
lifeExp      0
gdpPercap    0
dtype: int64

### Preparing summary table

In [34]:
summary_df = (
    development_df.groupby("continent")["lifeExp"]
    .mean()
    .reset_index(name="average_life_expectancy")
    .sort_values("average_life_expectancy", ascending=False)
)

summary_df

#The key idea is: grouping makes the continent names row labels; 
#reset_index() turns them back into a column

  continent  average_life_expectancy
4   Oceania                80.719500
3    Europe                77.648600
1  Americas                73.608120
2      Asia                70.728485
0    Africa                54.806038

In [35]:
#Now let's save the summary:
summary_df.to_csv("continent_life_expectancy_2007.csv", index=False)

In [36]:
#Connecting Jupyter to SQLite database
#First let's confirm that Python can find the existing database

from pathlib import Path

db_path = Path("world_development.db")

if not db_path.is_file():
    raise FileNotFoundError("Database not found in the project folder.")

In [37]:
#Connecting directly removes the manual step of exporting from DBeaver and importing the CSV into Jupyter. 
#You can rerun the code to retrieve the latest database data.

import sqlite3

connection = sqlite3.connect(db_path)

database_df = pd.read_sql_query(
    "SELECT * FROM development WHERE year = 2007;",
    connection
)

database_df.head()

       country  year       pop continent  lifeExp     gdpPercap
0  Afghanistan  2007  31889923      Asia   43.828    974.580338
1      Albania  2007   3600523    Europe   76.423   5937.029526
2      Algeria  2007  33333216    Africa   72.301   6223.367465
3       Angola  2007  12420476    Africa   42.731   4797.231267
4    Argentina  2007  40301927  Americas   75.320  12779.379640

In [44]:
#Checking how much data the query returned
database_df.shape

(142, 6)

In [39]:
#Close the database
connection.close()